name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlite-core >=0.3.0,<0.4.0
  - jupyterlite-xeus>=0.1.2,<0.2
  - jupyterlab
  - jupyter_packaging
  - notebook
  - voila-material
  - websockets
  - pip:
    - voila
    - voila-material
    - voici-core
